dataset:
  path: images/marker/dev1
  transforms:
    crop: [128, 128]
    resize: [64, 64]

loader:
  batch_size: 16
  shuffle: True

model:
  image_shape: [1, 64, 64]
  num_layer: 4
  base_channel: 8
  latent_size: 50


train:
  epoch: 3000
  lr: 0.001
  device: "cpu"
  save_interval: 100
  show_interval: 10
